{% set name = "cppTango" %}
{% set version = "9.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gitlab.com/tango-controls/{{ name }}/-/archive/{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8f8cd49d5287f66f84088a1cf2fa427c98a4a567fb81cce8479e1b14c4307b16

build:
  number: 1
  # Prevent libtango.so.{{ version }}.dbg to be modified
  # Will raise CRC mismatch otherwise!
  binary_relocation:                 # [linux]
    - lib/libtango.so.{{ version }}  # [linux]
  run_exports:
    - {{ pin_subpackage('cpptango', max_pin='x.x') }}

requirements:
  build:
    - cmake
    - make        # [unix]
    - {{ compiler('cxx') }}
    - libtool     # [unix]
    - pkg-config  # [unix]
    - omniorb >=4.3.0,<4.4.0a0  # [build_platform != target_platform]
  host:
    - omniorb >=4.3.0,<4.4.0a0
    # Explicitely define omniorb-libs here even if omniorb depends on it
    # otherwise it's not added in the run requirements on OSX (as specified in run_exports)
    - omniorb-libs
    - cppzmq
    - zeromq
    - tango-idl
    - libjpeg-turbo
    - pthreads-win32  # [win]
  run:
    - {{ pin_compatible('pthreads-win32', max_pin='x.x') }}  # [win]

test:
  commands:
    - test -f ${PREFIX}/lib/libtango${SHLIB_EXT}              # [unix]
    - test -f ${PREFIX}/lib/libtango.so.95                    # [linux]
    - test -f ${PREFIX}/lib/libtango.95.dylib                 # [osx]
    - test -f ${PREFIX}/lib/pkgconfig/tango.pc                # [unix]
    - test -f ${PREFIX}/include/tango/tango.h                 # [unix]
    - test -f ${PREFIX}/include/tango/idl/tango.h             # [unix]
    - if not exist %LIBRARY_BIN%\\tango.dll exit 1            # [win]
    - if not exist %LIBRARY_INC%\\tango\\tango.h exit 1       # [win]
    - if not exist %LIBRARY_INC%\\tango\\idl\\tango.h exit 1  # [win]
    - if not exist %LIBRARY_LIB%\\pkgconfig\\tango.pc exit 1  # [win]

outputs:                                                                 # [linux]
  - name: cpptango                                                       # [linux]
    files:                                                               # [linux]
      - lib/libtango.so                                                  # [linux]
      - lib/libtango.so.95                                               # [linux]
      - lib/libtango.so.{{ version }}                                    # [linux]
      - lib/pkgconfig/tango.pc                                           # [linux]
      - include/tango                                                    # [linux]

  - name: cpptango-dbg                                                   # [linux]
    requirements:                                                        # [linux]
      run:                                                               # [linux]
        - {{ pin_subpackage('cpptango', exact=True) }}                   # [linux]
    files:                                                               # [linux]
      - lib/libtango.so.{{ version }}.dbg                                # [linux]
    test:                                                                # [linux]
      commands:                                                          # [linux]
        - test -f ${PREFIX}/lib/libtango${SHLIB_EXT}.${PKG_VERSION}.dbg  # [linux]

about:
  home: https://www.tango-controls.org
  license: LGPL-3.0-or-later
  license_file: LICENSE
  summary: 'Tango-Controls C++ library'
  description: |
   This is the Tango-Controls C++ library (a.k.a. cppTango).
   Tango-Controls is a software toolkit for building control systems.
  dev_url: https://gitlab.com/tango-controls/cppTango
  doc_url: https://tango-controls.gitlab.io/cppTango/
  doc_source_url: https://gitlab.com/tango-controls/cppTango

extra:
  recipe-maintainers:
    - beenje
    - bourtemb
