{% set name = "cppTango" %}
{% set version = "9.3.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/tango-controls/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 50828ae9f523c8b2eeb546b38138b0d0882fcd3050e952d93a66a594ed178e72

build:
  number: 2
  skip: true  # [not linux]
  # Prevent libtango.so.{{ version }}.dbg to be modified
  # Will raise CRC mismatch otherwise!
  binary_relocation:
    - lib/libtango.so.{{ version }}
  run_exports:
    - {{ pin_subpackage('cpptango', max_pin='x.x') }}

requirements:
  build:
    - cmake
    - make
    - {{ compiler('cxx') }}
    - libtool
    - pkg-config
  host:
    - omniorb
    - cppzmq
    - zeromq
    - tango-idl
  run:
    - {{ pin_compatible('omniorb', max_pin='x.x') }}
    # zeromq max_pin set in pin_run_as_build in conda-forge-pinning
    - zeromq

test:
  commands:
    - test -f ${PREFIX}/lib/libtango${SHLIB_EXT}
    - test -f ${PREFIX}/lib/pkgconfig/tango.pc
    - test -f ${PREFIX}/include/tango/tango.h

outputs:
  - name: cpptango
    files:
      - lib/libtango.so
      - lib/libtango.so.9
      - lib/libtango.so.{{ version }}
      - lib/pkgconfig/tango.pc
      - include/tango

  - name: cpptango-dbg
    requirements:
      run:
        - {{ pin_subpackage('cpptango', exact=True) }}
    files:
      - lib/libtango.so.{{ version }}.dbg
    test:
      commands:
        - test -f ${PREFIX}/lib/libtango${SHLIB_EXT}.${PKG_VERSION}.dbg

about:
  home: https://www.tango-controls.org
  license: LGPL-3.0-or-later
  license_file: LICENSE
  summary: 'Tango-Controls C++ library'
  description: |
   This is the Tango-Controls C++ library (a.k.a. cppTango).
   Tango-Controls is a software toolkit for building control systems.
  dev_url: https://github.com/tango-controls/cppTango
  doc_url: https://tango-controls.github.io/cppTango-docs
  doc_source_url: https://github.com/tango-controls/cppTango-docs

extra:
  recipe-maintainers:
    - beenje
    - bourtemb
